#!/bin/bash

source SOURCEME


function h1() {
  echo -n "`printf '\n ---==:  %-25s  ' $1`"
}
function pass() {
  echo -n "."
}
function fail() {
  local txt='X'
  [[ -z "$@" ]] || txt+="[$@]"
  echo -n "$txt"
}
function skip() {
  echo -n 'S'
}
export -f pass fail skip h1


# source foo.sh


# maybe need an _.executeAll?
time _::util::source_all -r test/
# _::util::source_all -r test/_
# _::util::source_all -r test/array
# _::util::source_all -r test/date
# _::util::source_all -r test/cuz
# _::util::source_all -r test/lang
# _::util::source_all -r test/math
# _::util::source_all -r test/number
# _::util::source_all -r test/string
# _::util::source_all -r test/util
# echo "-> $?"
echo
