#!/bin/bash

source SOURCEME


function h1 {
  echo -n "`printf '\n ---==:  %-15s  ' $1`"
}
function pass {
  echo -n '.'
}
function fail {
  local txt='X'
  [[ -z "$@" ]] || txt+="[$@]"
  echo -n "$txt"
}
function skip {
  echo -n 'S'
}
export -f pass fail skip h1


# source foo.sh


# maybe need an _.executeAll?
time _sourceAll -r test/
# _sourceAll -r test/_
# _sourceAll -r test/array
# _sourceAll -r test/date
# _sourceAll -r test/cuz
# _sourceAll -r test/lang
# _sourceAll -r test/math
# _sourceAll -r test/number
# _sourceAll -r test/string
# _sourceAll -r test/utility
# echo "-> $?"
echo
