#!/bin/bash

source functions/cuz/sourceAll.sh
_.sourceAll -r -x functions


function h1 {
  # echo -n "\n ---== test: _.${1}"
  echo -n "`printf '\n ---==:  _.%-15s  ' $1`"
}
function pass {
  echo -n '.'
}
function fail {
  local txt='X'
  [ -n "$@" ] && txt+="[$@]"
  echo -n "$txt"
}
export -f pass fail h1


source foo.sh


# maybe need an _.executeAll?
time _.sourceAll -r test/
# echo "-> $?"
echo
